server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=40000&serverTimezone=GMT%2B8
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver