server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.11.11.188:3306/zf?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=40000&serverTimezone=GMT%2B8
    username: linkedme
    password: linkedme2016
    driver-class-name: com.mysql.cj.jdbc.Driver